apiVersion: v1
kind: Service
metadata:
  name: ddgqa-exposed
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.45
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: ddgqaport
  selector:
    app: ddg-qa-server
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ddgqa-api
  labels:
    app: ddg-qa-server
spec:
  ports:
  - port: 8000
    name: tcp-ddgqa-api
    protocol: TCP
    targetPort: ddgqaport
  type: NodePort
  selector:
    app: ddg-qa-server