kind: Deployment
apiVersion: apps/v1
metadata:
  name: ddg-qa-server
  labels:
    app: ddg-qa-server
  namespace: langchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddg-qa-server
  template:
    metadata:
      labels:
        app: ddg-qa-server
    spec:
      containers:
        - name: dda-qa-server
          image: gclef/langchain:0.1-ddgqa
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "5Gi"
          ports:
            - containerPort: 8000
              name: ddgqaport
              protocol: TCP
          env:
            - name: MODEL
              value: "/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
            - name: N_GPU_LAYERS
              value: "0"
            - name: N_CTX
              value: "4096"
            - name: N_BATCH
              value: "1024"
            - name: VECTOR_STORAGE_PATH
              value: "/scratch"
          volumeMounts:
            - name: models
              mountPath: /models
            - name: scratchspace
              mountPath: /scratch
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: langchain-pvc
        - name: scratchspace
          emptyDir:
---
