apiVersion: v1
kind: Service
metadata:
  name: wikirag-exposed
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.44
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: wikiragport
  selector:
    app: wikipedia-rag-server
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: wikirag-api
  labels:
    app: wikipedia-rag-server
spec:
  ports:
  - port: 8000
    name: tcp-wikirag-api
    protocol: TCP
    targetPort: wikiragport
  type: NodePort
  selector:
    app: wikipedia-rag-server