kind: Deployment
apiVersion: apps/v1
metadata:
  name: basic-chain-server
  labels:
    app: basic-chain-server
  namespace: langchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-chain-server
  template:
    metadata:
      labels:
        app: basic-chain-server
    spec:
      containers:
        - name: basic-chain-server
          image: gclef/langchain:0.1-basic
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "5Gi"
          ports:
            - containerPort: 8000
              name: basicchainport
              protocol: TCP
          env:
            - name: MODEL
              value: "/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
            - name: N_GPU_LAYERS
              value: "0"
            - name: N_CTX
              value: "1024"
            - name: N_BATCH
              value: "1024"
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: langchain-pvc
---
