architecture: standalone
auth:
  existingSecret: redis-secrets
master:
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 3Gi
  persistence:
    enabled: false
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.41
    annotations:
      metallb.universe.tf/address-pool: malwaretl-exposed

